### ISSUE TITLE
OAuth認証でGitHubへのログインを試す

### ISSUE THREAD

**Issue by ms2sato** [CircleAround/gbs#1]
http://studio-faust.com/programming/481/
こちらを元にして試すと良さそうです。

**Comment by ms2sato** [comment]
https://github.com/thephpleague/oauth2-client
https://github.com/adoy/PHP-OAuth2

こういうのもある模様

**Comment by ms2sato** [comment]
@rinkun CakePHP3ではOAuthログインのプラグインがない様子なのです。OAuthの簡単なやり方を調べておいて欲しいです。使うのはGitHubねー。

**Comment by ms2sato** [comment]
まだ実装はしないでOKです。サンプル作っておくのは超ありです！

**Comment by papagram** [comment]
@ms2sato 
https://github.com/usemuffin/oauth2
こんなのも見つけました。

**Comment by papagram** [comment]
@ms2sato https://github.com/thephpleague/oauth2-client ご紹介いただいたライブラリを使って、一応プロフィール情報の取得には成功しました。

**Comment by ms2sato** [comment]
![LGTM](http://www.troll.me/images/bush/looks-good-to-me-ship-it.jpg) 
thanks!
