### ISSUE TITLE
Threadのコメント修正したら、コメントしたThreadに戻るようにする

### ISSUE THREAD

**Issue by ms2sato** [CircleAround/gbs#103]
> comment#edit後、thread#viewではなく、comment#indexに飛んでしまっています。

とのことなので、修正します！

**Comment by Kojima87** [comment]
@ms2sato comment#deleteも、comment#indexに飛んでしまっているのですが、別のIssueを立てますか？

**Comment by ms2sato** [comment]
@Kojima87 このIssueでやりましょう！
