### ISSUE TITLE
セッションに入っているユーザIDに対応したユーザがいないと例外になっちゃう

### ISSUE THREAD

**Issue by ms2sato** [CircleAround/gbs#126]
この場合、セッション情報を全て消してトップへ遷移するべし。
可能ならログには出したい。

**Comment by ms2sato** [comment]
@makasn 最近忙しそうだと思いますので、`WIP`つけて`PR`だけ送ってしまってください。こちらで巻き取りますー。

**Comment by makasn** [comment]
@ms2sato すみません、こちらはほとんど進んでないのでそのままリリースさせていただきます。
無駄に持ってしまっててすみません。

**Comment by ms2sato** [comment]
了解しましたー

**Comment by ms2sato** [comment]
@Kojima87 こちら見てみてくださいー。

**Comment by Kojima87** [comment]
@ms2sato 着手するのが遅くなり、申し訳ありません！
こちらですが、
セッション情報が書き換わってしまった、とかですか？
すみません、
バグを再現して確認したいのですが、どのようにすればよいでしょう。
セッション情報を全て消すとは、
$_SESSION = array();
ログに出す情報はセッション情報ですか。
質問ばかりですみません。お手隙の際に教えていただけますと幸いです。
どうぞよろしくお願いいたします。

**Comment by ms2sato** [comment]
@Kojima87 わーん、確かにこの状況作りづらいんだ。バグと思ったのだけど、今まだ対応すべきほどの内容じゃないと判断しました。ごめんなさい〜。一度取り下げます。
