### ISSUE TITLE
Commentのバリデーション

### ISSUE THREAD

**Issue by ms2sato** [CircleAround/gbs#15]
CakePHPでDB設定からサポートしてくれているとは思うのですが、モデルのバリデーションを入れたいです。

基本的にはnot_null制約ばかりですが、入れましょう。`/comments`から新規作成と更新をした時に問題なく制約されていればOKです。（テストの環境が整ったら別途UnitテストIssueを作ります）。

ER図はこちら
https://cacoo.com/diagrams/v7ra1xlfADSpyyac/edit

http://book.cakephp.org/3.0/ja/core-libraries/validation.html
公式のドキュメントはこちら

下記はどうやって入れるかの参考にはなるでしょう。
http://w.builwing.info/2015/05/03/cakephp3-0%E3%81%AE%E3%83%96%E3%83%AD%E3%82%B0%E3%83%81%E3%83%A5%E3%83%BC%E3%83%88%E3%83%AA%E3%82%A2%E3%83%AB/

迷ったら質問下さいー。

**Comment by ms2sato** [comment]
@Skk395 割り当てました！よろしくお願いしますー。疑問点などあったら聞いて下さい。

**Comment by ms2sato** [comment]
@Skk395 ごめんよー。Scaffold でデフォルトが作られるんですね。デフォルトで作成されているバリデーションが妥当かどうかは見てもらって、もしもコードを弄らなくて良さそうなら報告くれたら確認します！

**Comment by cha3** [comment]
http://blog.xao.jp/blog/cakephp/memo-of-preparing-for-migration-to-cakephp3/

Scaffold 廃止されているみたいです

**Comment by cha3** [comment]
あーすみません！　初sorce treeでコミット失敗しているかもしれません・・・
それ含めみてもらえますか？
closed #15

**Comment by cha3** [comment]
@ms2sato ご確認お願いしますー（つけ忘れましたw）

**Comment by ms2sato** [comment]
@Skk395 

> Scaffold 廃止されているみたいです

Oh!ホントだ。気づいていなかったです。ありがとう。
今後は検討せねばなるまい。

> closed #15
> @ms2sato ご確認お願いしますー（つけ忘れましたw）

こちらは PR につければ大丈夫！ アサインもPRの方でやってくだされ。
（私が意識するのはIssueではなくて PR だけになるはず。仕様の相談をする時にはIssueに書いたりします。）
