### ISSUE TITLE
Threadのバリデーション

### ISSUE THREAD

**Issue by ms2sato** [CircleAround/gbs#16]
CakePHPでDB設定からサポートしてくれているとは思うのですが、モデルのバリデーションを入れたいです。

基本的にはnot_null制約ばかりですが、入れましょう。`/threads`から新規作成と更新をした時に問題なく制約されていればOKです。（テストの環境が整ったら別途UnitテストIssueを作ります）。

ER図はこちら
https://cacoo.com/diagrams/v7ra1xlfADSpyyac/edit

http://book.cakephp.org/3.0/ja/core-libraries/validation.html
公式のドキュメントはこちら

下記はどうやって入れるかの参考にはなるでしょう。
http://w.builwing.info/2015/05/03/cakephp3-0%E3%81%AE%E3%83%96%E3%83%AD%E3%82%B0%E3%83%81%E3%83%A5%E3%83%BC%E3%83%88%E3%83%AA%E3%82%A2%E3%83%AB/

迷ったら質問下さいー。

**Comment by ms2sato** [comment]
@makasn ごめんよー。Scaffold でデフォルトが作られるんですね。デフォルトで作成されているバリデーションが妥当かどうかは見てもらって、もしもコードを弄らなくて良さそうなら報告くれたら確認します！

**Comment by makasn** [comment]
@ms2sato こちらこそ、遅くなってしまってすみません。デフォルトで作られているものを確認しました！ER図を見た感じではnot_null制約のみでデフォルトのものをそのまま使って問題ないと思います。
ご確認よろしくお願いします！

**Comment by ms2sato** [comment]
問題なしと確認されたのでclose
