### ISSUE TITLE
トップページの内容を `/threads`と同一にする

### ISSUE THREAD

**Issue by ms2sato** [CircleAround/gbs#32]
`route`を調整して、 `/` にアクセスしたら スレッド一覧が表示されるようにして下さい。

**Comment by ms2sato** [comment]
@Kojima87 一旦調査してみてください。情報があったらこのIssueに貼ってもらって、それから実際に実装しましょう。

**Comment by Kojima87** [comment]
## http://book.cakephp.org/3.0/ja/development/routing.html

use Cake\Routing\Router;

// カッコで囲まれたルーティングビルダーを使います。
Router::scope('/', function ($routes) {
    $routes->connect('/', ['controller' => 'Articles', 'action' => 'index']);
});

// 静的メソッドを使います。

## Router::connect('/', ['controller' => 'Articles', 'action' => 'index']);

@ms2sato このことでしょうか。

**Comment by ms2sato** [comment]
@Kojima87 OKです！今のルーティングに合わせて上記の２つの方法のどちらかを適用すると良いでしょう。実装お願いします！

**Comment by Kojima87** [comment]
@ms2sato 承知しました。

**Comment by ms2sato** [comment]
宜しくお願いしまっす！
