### ISSUE TITLE
usersテーブルの内容を ER図に追記

### ISSUE THREAD

**Issue by ms2sato** [CircleAround/gbs#34]
https://cacoo.com/diagrams/v7ra1xlfADSpyyac
usersの情報が入っていないので入れてあげて下さい。not_nullなどの制約も入れて欲しいです。迷ったら @ms2sato まで相談下さい。

**Comment by papagram** [comment]
@ms2sato できました。

**Comment by ms2sato** [comment]
確認しました！

![LGTM](https://pbs.twimg.com/profile_images/378800000726546064/581c4f4d059cd2f69261de0efb76fb22_400x400.png)
