### ISSUE TITLE
Commentのマイグレーション

### ISSUE THREAD

**Issue by ms2sato** [CircleAround/gbs#5]
https://github.com/CircleAround/gbs/wiki/%E3%83%9E%E3%82%A4%E3%82%B0%E3%83%AC%E3%83%BC%E3%82%B7%E3%83%A7%E3%83%B3%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6
を参考にする

**Comment by Kojima87** [comment]
@ms2sato Commentのマイグレーション、PRしました。別にエラーが１件でています。ご確認をお願いします。
