### ISSUE TITLE
ログインしていないと入れない画面を弾く実装

### ISSUE THREAD

**Issue by ms2sato** [CircleAround/gbs#55]
#53 が終わったらやること
- [ ] ログインしていない人が特定の画面に入ろうとしたり、POSTしようとしたりした時に拒絶できる仕組みを調べる。
- [ ] 上記を利用して実装を入れる（今は入っていけない画面は殆ど無いので、サンプル的な実装が欲しいです）。

**Comment by ms2sato** [comment]
@Kojima87 少し難しいかもしれないので、まずは調べてみてください。このIssue上で実装の提案をください。コミュニケーションしてから実装という流れにしましょう。

**Comment by Kojima87** [comment]
@ms2sato 現在、以下を見ています。全然違っていましたら、ご指摘いただけると大変助かります。

AuthComponent::allow()を使って、許可するアクションを設定、または、
AuthComponent::deny()を使って、許可しないアクションを設定する。
たとえば、Controller内で、
    public function beforeFilter(Event $event)
    {
        parent::beforeFilter($event);
        $this->Auth->allow(‘view’);
    }

どういうふうに動作するのかわかっていません。
そして、ここでログインしていなかったらログイン画面にリダイレクトする？
・・・中途半端ですみません。

**Comment by ms2sato** [comment]
@Kojima87 なるほど！ 今の実装は AuthComponentを利用していないので、この方法はちょっと使わないですー。

でも、beforeFileterでログインしているかを判断するのはGoodですね！
AppController#isLoggedIn という関数があるので、その中でこちらを使うとログインしているかどうかの判断ができますよー。

これで少し理解が進みますか？ :smile:

**Comment by Kojima87** [comment]
@ms2sato ありがとうございます！
actionが、indexやviewのときは、ログインしていなくてもいいので、
そういった判断を含めてbeforeFileterに書くのですね。
「Event $event」これかな・・

**Comment by ms2sato** [comment]
@Kojima87 惜しい！書きが参考になるかな？

http://book.cakephp.org/3.0/en/controllers/request-response.html#request-parameters

**Comment by Kojima87** [comment]
@ms2sato ありがとうございます。AppControllerに、以下のように書けそうです。
    public function beforeFilter() {
        $action = $this->request->params['action'];
        if($action != 'index' and $action != 'view' and $this->isLoggedIn()){
          // ログインへ遷移、メッセージのみ、など処理を書く＊
        }
    }
＊に書く処理としては、
・ログイン画面に遷移する
または、
・「ログインしてね」メッセージを出して、画面遷移しないように留めるかトップへ遷移する

**Comment by ms2sato** [comment]
@Kojima87 お、いい感じっぽい。

AppController に `index`アクションと`view`アクション以外、と入れてしまうとちょっと大雑把になってしまうので、下記のようにしましょうか。
- `AppController#shouldLogin` を作成。falseを返しておく。
- `AppController#beforeFilter` で、 `$this->shouldLogin()`が真ならログインして欲しい時の処理
  - ログインしてねメッセージを出す & とりあえずトップに遷移して良いです。
- `ThreadsController#shouldLogin`、`CommentsController#shouldLogin` で下記のようなロジック。

``` rb
$action = $this->request->params['action'];
if($action != 'index' and $action != 'view' and $this->isLoggedIn()){
  return true;
}
return false;
```

**Comment by Kojima87** [comment]
@ms2sato ありがとうございます！　上記で実装してよろしいでしょうか。

**Comment by ms2sato** [comment]
@Kojima87 お願いしまーす。

**Comment by Kojima87** [comment]
@ms2sato 承知しました。
