### ISSUE TITLE
threads/view/:id のコメントをtextareaで入力できるようにする

### ISSUE THREAD

**Issue by ms2sato** [CircleAround/gbs#59]
今はテキストフィールドなので、長文テキストが入れにくいですよね！

**Comment by Kojima87** [comment]
input の型はテーブルのカラムのデータ型に依存するはずなのに、ここだけ変ですね。。
調べます。
@ms2sato なにかヒントがあれば、お知らせいただけると大変助かります。

**Comment by ms2sato** [comment]
@Kojima87 まだこちらはassignしていないので対応しなくて大丈夫ですよ。別の方にお願いするかもーという感じです。まずは幹になるところを中心にやろうと思っています！

**Comment by ms2sato** [comment]
積極的な対応に感謝！

**Comment by Kojima87** [comment]
@ms2sato すみません！　ちゃんと見ていませんでしたー
で、ここは自身で書いたFormなので、カラムのデータ型の話ではありませんでした。
先ずはassignされた場所を見ます。

**Comment by ms2sato** [comment]
了解です〜 :smile: お願いしまーす。

**Comment by ms2sato** [comment]
@makasn ちょっと本件調査からお願いしまっす！
