### ISSUE TITLE
thread#edit、comment#edit の各画面から actor_idの指定をさせないように消す。

### ISSUE THREAD

**Issue by ms2sato** [CircleAround/gbs#69]
Thread の edit で actor を外しちゃいましょう！
Commentの edit でも actorを外しちゃいましょう！

**Comment by ms2sato** [comment]
@Kojima87 一旦アサイン変更しました。簡単なIssueですがこちらをやりましょう！

**Comment by Kojima87** [comment]
@ms2sato すでにコメントアウトされていますが、このコメント自体を削除るのでしょうか。

**Comment by Kojima87** [comment]
@ms2sato すみません！　間違えました！　actor入力を外します。
