### ISSUE TITLE
Emailが取れない場合があるので対応する

### ISSUE THREAD

**Issue by ms2sato** [CircleAround/gbs#73]
GitHub上のSettingでemailをpublic にしてない人は 取れないっぽい。まず GitHub側の設定とどういう関係があるか確かめて下さい。その結果をこのIssueに書いていただいて、その後進めます。

下記二箇所くらいが関係ありそう。どっちがどのように関係するかは未確認。どちらかをいじるとE-mailが取れない状況が再現できるはず。

![email settings](https://cloud.githubusercontent.com/assets/627817/10558405/35687f6a-7508-11e5-896a-adbbeb17d6b5.png)

![your profile](https://cloud.githubusercontent.com/assets/627817/10558406/399f75a2-7508-11e5-9384-d8f08f898009.png)

**Comment by makasn** [comment]
@ms2sato 結論から言うと、Public emailが設定されていない("Don't show my email address")になっている場合はemailが取れないです。また、Keep my email address privateはチェック入っていても入っていなくても関係ないみたいなので、Your primary GitHub email address will....がprivateになっていても大丈夫なようです。要はPublic emailが設定されていればemailを取ってこれますー。

**Comment by ms2sato** [comment]
@makasn 調査ありがとう。 もしもE-mailが取れなかった場合には、E-mail入力のダイアログを出した後、ユーザ登録を完了したいです。
- 画面作成（src/Template/Oauth/edit）
- ロジック調整（OauthController）

な感じかと思います。ちょっと大きめに渡しますができそうですか？
