### ISSUE TITLE
Commentモデルのユニットテストを実装する。

### ISSUE THREAD

**Issue by Kojima87** [CircleAround/gbs#85]
基本的な動作のテストを実装する。

**Comment by Kojima87** [comment]
@ms2sato さんへ
Commentの編集画面で、ThreadとActorが入力できるようになっています。これは間違いで、Bodyのみが入力項目でよろしいでしょうか。

**Comment by ms2sato** [comment]
@Kojima87 その通りです！今後対応されていきます！
