### ISSUE TITLE
ThreadControllerのテスト

### ISSUE THREAD

**Issue by ms2sato** [CircleAround/gbs#89]
ThreadControllerのテストを書いてみましょう。
例のごとく書き方については一度調べてみてください。
雛形は既にあると思うので、中身を埋めてゆく作業になります。

**Comment by Kojima87** [comment]
@ms2satoさんへ、
正しいデータ、変なデータによって、設定されたflash文言が出ることを確認、
リダイレクト先も確認する、のような感じでよろしいでしょうか。

**Comment by ms2sato** [comment]
@Kojima87 返信遅れてごめんなさいー。

http://book.cakephp.org/3.0/ja/development/testing.html#return
この辺りが参考になると思います。
基本的には
- 画面描画に選ばれたテンプレートの確認`view`
- 画面側に返されたデータ`vars`

をチェックするのが基本でしょう。 `flash`文言チェックがあると尚よし、ですね。
もしもやってみて微妙な様子だったら質問ください！
